"use client";
import type { Metadata } from "next";
import { ThemeProvider, CssBaseline, Box } from "@mui/material";
import muiTheme from "../styles/muiTheme";
import { usePathname } from "next/navigation"; // Use `usePathname` in Next.js 14
import { PROTECTED_ROUTES } from "@/utils/constants";
import "../styles/global.css";
import AlertStack from "@/components/shared/AlertStack";
import StoreProvider from "./StoreProvider";
import MiniDrawer from "@/components/shared/MiniDrawer";
import PermanentDrawerLeft from "@/components/shared/PermanentDrawerLeft";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); 
  

  return (
    <ThemeProvider theme={muiTheme}>
      <CssBaseline />
      <StoreProvider>
        <html lang="en">
          <body className="bg-white">
            {PROTECTED_ROUTES.includes(pathname) ? (
              <PermanentDrawerLeft pathName={pathname}>
                {children}
              </PermanentDrawerLeft>
            ) : (
              <Box>{children}</Box>
            )}

            <AlertStack />
          </body>
        </html>
      </StoreProvider>
    </ThemeProvider>
  );
}
